In [86]:
import pandas as pd
diabetes = pd.read_csv("diabetes.csv")
heart = pd.read_csv("heart_statlog_cleveland_hungary_final.csv")
liver = pd.read_csv("indian_liver_patient.csv")
kidney = pd.read_csv("kidney_disease.csv")
print(diabetes.head())
print(heart.head())
print(liver.head())
print(kidney.head())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
   age  sex  chest pain type  resting bp s  cholesterol  fasting blood sugar  \
0   40    1                2           140          289                    0   
1   49    0                3           160          180                    0   
2   37    1                2           130          283        

In [87]:
diabetes["disease"] = diabetes["Outcome"].replace({1: "Diabetes", 0: "No Diabetes"})
heart["disease"] = heart["target"].replace({1: "Heart Disease", 0: "No Heart Disease"})
kidney["disease"] = kidney["classification"].replace({"ckd": "CKD", "notckd": "No CKD"})
liver["disease"] = liver["Dataset"].replace({1: "Liver Disease", 2: "No Liver Disease"})
diabetes.drop(['Outcome'],inplace=True,axis=1)
heart.drop(['target'],axis=1)
kidney.drop(['classification'],axis=1)
liver.drop(['Dataset'],axis=1)

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65  Female              0.7               0.1                   187   
1     62    Male             10.9               5.5                   699   
2     62    Male              7.3               4.1                   490   
3     58    Male              1.0               0.4                   182   
4     72    Male              3.9               2.0                   195   
..   ...     ...              ...               ...                   ...   
578   60    Male              0.5               0.1                   500   
579   40    Male              0.6               0.1                    98   
580   52    Male              0.8               0.2                   245   
581   31    Male              1.3               0.5                   184   
582   38    Male              1.0               0.3                   216   

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio           disease  
0        3.3                        0.90     Liver Disease  
1        3.2                        0.74     Liver Disease  
2        3.3                        0.89     Liver Disease  
3        3.4                        1.00     Liver Disease  
4        2.4                        0.40     Liver Disease  
..       ...                         ...               ...  
578      1.6                        0.37  No Liver Disease  
579      3.2                        1.10     Liver Disease  
580      3.2                        1.00     Liver Disease  
581      3.4                        1.00     Liver Disease  
582      4.4                        1.50  No Liver Disease  

[583 rows x 11 columns]

In [88]:
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age      disease  
0                     0.627   50     Diabetes  
1                     0.351   31  No Diabetes  
2                     0.672   32     Diabetes  
3                     0.167   21  No Diabetes  
4                     2.288   33     Diabetes

In [89]:
diabetes.shape


(768, 9)

In [90]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

In [91]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
db = diabetes['disease']
diabetes['disease_int'] = db.replace({'Diabetes':1,'No Diabetes':0})
diabetes.drop(['disease'],axis=1,inplace = True)

C:\Users\HARISH\AppData\Local\Temp\ipykernel_15532\652878696.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  diabetes['disease_int'] = db.replace({'Diabetes':1,'No Diabetes':0})


In [92]:
print(diabetes['disease_int'].value_counts())

disease_int
0    500
1    268
Name: count, dtype: int64


In [93]:
X = diabetes.drop(['disease_int'],axis=1)
Y = diabetes['disease_int']



In [94]:
print(len(X.columns))


8


In [95]:
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  disease_int  
0                     0.627   50            1  
1                     0.351   31            0  
2                     0.672   32            1  
3                     0.167   21            0  
4                     2.288   33            1

In [96]:
diabetes.fillna(method='bfill',inplace=True)

C:\Users\HARISH\AppData\Local\Temp\ipykernel_15532\2897231439.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  diabetes.fillna(method='bfill',inplace=True)


In [97]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42,stratify=Y)

In [98]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
x_train_resampled, y_train_resampled = smote.fit_resample(x_train, y_train)


In [99]:
diabetes_scaler = StandardScaler()
x_train_scale = diabetes_scaler.fit_transform(x_train_resampled)
x_test_scale = diabetes_scaler.transform(x_test)

In [100]:
model = RandomForestClassifier(n_estimators=450,max_depth=5,random_state=42,class_weight='balanced')
model.fit(x_train_scale,y_train_resampled)
y_pred = model.predict(x_test_scale)

In [101]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.7662337662337663

In [122]:

import numpy as np
sample_input_low = np.array([[1, 95, 70, 20, 80, 24.5, 0.2, 25]])   
sample_input_med = np.array([[3, 130, 82, 30, 180, 32.5, 0.45, 40]])  
sample_input_high = np.array([[6, 180, 95, 40, 350, 38.7, 1.2, 55]])  


sample = sample_input_med

scaled_sample = diabetes_scaler.transform(sample)


prediction = model.predict(scaled_sample)
probability = model.predict_proba(scaled_sample)[0][1]

print("DIABETES MODEL TEST")
print("Prediction:", prediction)
print("Probability:", probability)


if probability < 0.4:
    print("Risk Level: LOW")
elif probability < 0.75:
    print("Risk Level: MEDIUM")
else:
    print("Risk Level: HIGH")

C:\Users\HARISH\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


DIABETES MODEL TEST
Prediction: [1]
Probability: 0.7465567581975552
Risk Level: MEDIUM


In [104]:
print(list(X.columns))

['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']


In [106]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, roc_auc_score
import numpy as np


cv_scores = cross_val_score(model, x_train_resampled, y_train_resampled, cv=5, scoring='accuracy')
print("Cross-validation Accuracy scores:", cv_scores)
print("Mean CV Accuracy:", np.mean(cv_scores))

y_pred = model.predict(x_train_resampled)

print("TRAIN SET METRICS")
print("Accuracy:", accuracy_score(y_train_resampled, y_pred))
print("Precision:", precision_score(y_train_resampled, y_pred, average='weighted'))
print("Recall:", recall_score(y_train_resampled, y_pred, average='weighted'))
print("F1-score:", f1_score(y_train_resampled, y_pred, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_train_resampled, y_pred))
print("\n")


y_test_pred = model.predict(x_test_scale)

print("TEST SET METRICS")
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision:", precision_score(y_test, y_test_pred, average='weighted'))
print("Recall:", recall_score(y_test, y_test_pred, average='weighted'))
print("F1-score:", f1_score(y_test, y_test_pred, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))
print("\nClassification Report:\n", classification_report(y_test, y_test_pred))


if len(set(y_test)) == 2:
    y_test_prob = model.predict_proba(x_test_scale)[:, 1]
    auc = roc_auc_score(y_test, y_test_prob)
    print("ROC-AUC:", auc)

Cross-validation Accuracy scores: [0.75625 0.7625  0.76875 0.79375 0.81875]
Mean CV Accuracy: 0.78
TRAIN SET METRICS
Accuracy: 0.5
Precision: 0.25
Recall: 0.5


C:\Users\HARISH\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\HARISH\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


F1-score: 0.33333333333333326
Confusion Matrix:
 [[  0 400]
 [  0 400]]


TEST SET METRICS
Accuracy: 0.7662337662337663
Precision: 0.7880283191500701
Recall: 0.7662337662337663
F1-score: 0.7708489289663272
Confusion Matrix:
 [[75 25]
 [11 43]]

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.75      0.81       100
           1       0.63      0.80      0.70        54

    accuracy                           0.77       154
   macro avg       0.75      0.77      0.76       154
weighted avg       0.79      0.77      0.77       154

ROC-AUC: 0.8383333333333334


In [107]:
kidney['disease'].unique()

array(['CKD', 'ckd\t', 'No CKD'], dtype=object)

In [108]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier

In [109]:
db = kidney['disease'].astype(str).str.strip().str.lower()
kidney['disease_int'] = db.replace({'ckd': 1, 'no ckd': 0})
kidney.replace(['?', '\t?'], np.nan, inplace=True)
kidney.fillna(method='bfill', inplace=True)
kidney.fillna(method='ffill', inplace=True)
kidney.head()

C:\Users\HARISH\AppData\Local\Temp\ipykernel_15532\2754046928.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  kidney['disease_int'] = db.replace({'ckd': 1, 'no ckd': 0})
C:\Users\HARISH\AppData\Local\Temp\ipykernel_15532\2754046928.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  kidney.fillna(method='bfill', inplace=True)
C:\Users\HARISH\AppData\Local\Temp\ipykernel_15532\2754046928.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  kidney.fillna(method='ffill', inplace=True)


id   age    bp     sg   al   su     rbc        pc         pcc          ba  \
0   0  48.0  80.0  1.020  1.0  0.0  normal    normal  notpresent  notpresent   
1   1   7.0  50.0  1.020  4.0  0.0  normal    normal  notpresent  notpresent   
2   2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3   3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4   4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   

   ...   rc  htn   dm  cad  appet   pe  ane classification disease disease_int  
0  ...  5.2  yes  yes   no   good   no   no            ckd     CKD           1  
1  ...  3.9   no   no   no   good   no   no            ckd     CKD           1  
2  ...  3.9   no  yes   no   poor   no  yes            ckd     CKD           1  
3  ...  3.9  yes   no   no   poor  yes  yes            ckd     CKD           1  
4  ...  4.6   no   no   no   good   no   no            ckd     CKD           1  

[5 rows x 28 columns]

In [110]:
kidney.fillna(method='bfill',inplace=True)
kidney.drop(['rbc','pc','pcc','ba','htn','cad','appet','dm','pe','ane','classification','disease','id'],axis='columns',inplace=True)

C:\Users\HARISH\AppData\Local\Temp\ipykernel_15532\2417019525.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  kidney.fillna(method='bfill',inplace=True)


In [111]:
X = kidney.drop(['disease_int'],axis='columns')
Y = kidney['disease_int']
Y.value_counts()

disease_int
1    250
0    150
Name: count, dtype: int64

In [112]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42,stratify=Y)

In [113]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
x_train_resampled, y_train_resampled = smote.fit_resample(x_train, y_train)


In [114]:
kidney_scaler = StandardScaler()
x_train_scale = kidney_scaler.fit_transform(x_train_resampled)
x_test_scale = kidney_scaler.transform(x_test)

In [115]:
model1 = RandomForestClassifier(n_estimators=450,max_depth=5,random_state=42,class_weight='balanced')
model1.fit(x_train_scale,y_train_resampled)
y_pred = model1.predict(x_test_scale)

In [116]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

1.0

In [117]:
print(list(X.columns))

['age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc']


In [121]:

import numpy as np
sample_input_low = np.array([[30,80, 1.020, 0, 0,95,30,0.9, 140, 4.2,14,42,8000,5.0]])   
sample_input_med = np.array([[55,115, 1.150, 1, 1,190,80,1.1, 190, 5.9,20,46,10000,6.0]])  
sample_input_high = np.array([[70,110, 2.020, 3, 3,260,120,5.0, 130, 6.0,8,25,13000,3.0]]) 


sample = sample_input_med

scaled_sample = kidney_scaler.transform(sample)


prediction = model1.predict(scaled_sample)
probability = model1.predict_proba(scaled_sample)[0][1]

print("KIDNEY MODEL TEST")
print("Prediction:", prediction)
print("Probability:", probability)


if probability < 0.4:
    print("Risk Level: LOW")
elif probability < 0.75:
    print("Risk Level: MEDIUM")
else:
    print("Risk Level: HIGH")

KIDNEY MODEL TEST
Prediction: [1]
Probability: 0.7063985471421323
Risk Level: MEDIUM


C:\Users\HARISH\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [123]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, roc_auc_score
import numpy as np


cv_scores = cross_val_score(model1, x_train_scale, y_train_resampled, cv=5, scoring='accuracy')
print("Cross-validation Accuracy scores:", cv_scores)
print("Mean CV Accuracy:", np.mean(cv_scores))



y_pred = model1.predict(x_train_scale)

print("TRAIN SET METRICS")
print("Accuracy:", accuracy_score(y_train_resampled, y_pred))
print("Precision:", precision_score(y_train_resampled, y_pred, average='weighted'))
print("Recall:", recall_score(y_train_resampled, y_pred, average='weighted'))
print("F1-score:", f1_score(y_train_resampled, y_pred, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_train_resampled, y_pred))
print("\n")


y_test_pred = model1.predict(x_test_scale)

print("TEST SET METRICS")
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision:", precision_score(y_test, y_test_pred, average='weighted'))
print("Recall:", recall_score(y_test, y_test_pred, average='weighted'))
print("F1-score:", f1_score(y_test, y_test_pred, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))
print("\nClassification Report:\n", classification_report(y_test, y_test_pred))


if len(set(y_test)) == 2:
    y_test_prob = model1.predict_proba(x_test_scale)[:, 1]
    auc = roc_auc_score(y_test, y_test_prob)
    print("ROC-AUC:", auc)

Cross-validation Accuracy scores: [1.     1.     1.     1.     0.9875]
Mean CV Accuracy: 0.9974999999999999
TRAIN SET METRICS
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-score: 1.0
Confusion Matrix:
 [[200   0]
 [  0 200]]


TEST SET METRICS
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-score: 1.0
Confusion Matrix:
 [[30  0]
 [ 0 50]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        30
           1       1.00      1.00      1.00        50

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80

ROC-AUC: 1.0


In [124]:
heart.head()

age  sex  chest pain type  resting bp s  cholesterol  fasting blood sugar  \
0   40    1                2           140          289                    0   
1   49    0                3           160          180                    0   
2   37    1                2           130          283                    0   
3   48    0                4           138          214                    0   
4   54    1                3           150          195                    0   

   resting ecg  max heart rate  exercise angina  oldpeak  ST slope  target  \
0            0             172                0      0.0         1       0   
1            0             156                0      1.0         2       1   
2            1              98                0      0.0         1       0   
3            0             108                1      1.5         2       1   
4            0             122                0      0.0         1       0   

            disease  
0  No Heart Disease  
1     Heart Disease  
2  No Heart Disease  
3     Heart Disease  
4  No Heart Disease

In [125]:
heart.shape

(1190, 13)

In [126]:
heart['disease'].unique()

array(['No Heart Disease', 'Heart Disease'], dtype=object)

In [127]:
heart['disease'].value_counts()

disease
Heart Disease       629
No Heart Disease    561
Name: count, dtype: int64

In [128]:

db = heart['disease'].astype(str).str.strip().str.lower()
heart['disease_int'] = db.replace({'heart disease':1,'no heart disease':0})
heart.drop(['disease'],axis=1,inplace=True)
heart['disease_int'].value_counts()

C:\Users\HARISH\AppData\Local\Temp\ipykernel_15532\2399443820.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  heart['disease_int'] = db.replace({'heart disease':1,'no heart disease':0})


disease_int
1    629
0    561
Name: count, dtype: int64

In [129]:
heart.head()

age  sex  chest pain type  resting bp s  cholesterol  fasting blood sugar  \
0   40    1                2           140          289                    0   
1   49    0                3           160          180                    0   
2   37    1                2           130          283                    0   
3   48    0                4           138          214                    0   
4   54    1                3           150          195                    0   

   resting ecg  max heart rate  exercise angina  oldpeak  ST slope  target  \
0            0             172                0      0.0         1       0   
1            0             156                0      1.0         2       1   
2            1              98                0      0.0         1       0   
3            0             108                1      1.5         2       1   
4            0             122                0      0.0         1       0   

   disease_int  
0            0  
1            1  
2            0  
3            1  
4            0

In [130]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [131]:
X = heart.drop(['disease_int','target'],axis=1)
Y = heart['disease_int']
x_train,x_test,y_train,y_test = train_test_split(X,Y,random_state=42,test_size=0.2)

In [133]:
heart.fillna(method='bfill',inplace=True)

C:\Users\HARISH\AppData\Local\Temp\ipykernel_15532\607734603.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  heart.fillna(method='bfill',inplace=True)


In [135]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
x_train_resampled, y_train_resampled = smote.fit_resample(x_train, y_train)


In [136]:
heart_scaler = StandardScaler()
x_train_scale = heart_scaler.fit_transform(x_train_resampled)
x_test_scale = heart_scaler.transform(x_test)


In [137]:
model2 = RandomForestClassifier(n_estimators=450,max_depth=5,random_state=42,class_weight='balanced')
model2.fit(x_train_scale,y_train_resampled)
y_pred = model2.predict(x_test_scale)

In [138]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.907563025210084

In [139]:
print(heart['disease_int'].value_counts())

disease_int
1    629
0    561
Name: count, dtype: int64


In [140]:
print(len(X.columns))

11


In [141]:
print(list(X.columns))

['age', 'sex', 'chest pain type', 'resting bp s', 'cholesterol', 'fasting blood sugar', 'resting ecg', 'max heart rate', 'exercise angina', 'oldpeak', 'ST slope']


In [142]:

sample_input_low = np.array([[35, 1, 0, 115, 185, 0, 0, 178, 0, 0.0, 2]])  
sample_input_med = np.array([[64, 1, 3, 155, 280, 0, 1, 180, 0, 1.5, 2]])  
sample_input_high = np.array([[75, 0, 4, 165, 300, 1, 2, 165, 1, 1.5, 2]]) 

sample = sample_input_med

scaled_sample = heart_scaler.transform(sample)

prediction = model2.predict(scaled_sample)
probability = model2.predict_proba(scaled_sample)[0][1]

print("HEART MODEL TEST")
print("Scaled Input:", scaled_sample)
print("Predicted Class:", prediction)
print("Probability of disease:", probability)
if probability < 0.4:
    print("Risk Level: LOW")
elif probability < 0.65:
    print("Risk Level: MEDIUM")
else:
    print("Risk Level: HIGH")

C:\Users\HARISH\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


HEART MODEL TEST
Scaled Input: [[ 1.09376981  0.58662557 -0.20777639  1.25219971  0.7067997  -0.50908311
   0.36509944  1.56412415 -0.75235479  0.55651268  0.64808143]]
Predicted Class: [1]
Probability of disease: 0.5230086931356953
Risk Level: MEDIUM


In [143]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, roc_auc_score
import numpy as np

cv_scores = cross_val_score(model2, x_train_scale, y_train_resampled, cv=5, scoring='accuracy')
print("Cross-validation Accuracy scores:", cv_scores)
print("Mean CV Accuracy:", np.mean(cv_scores))

y_pred = model2.predict(x_train_scale)

print("TRAIN SET METRICS")
print("Accuracy:", accuracy_score(y_train_resampled, y_pred))
print("Precision:", precision_score(y_train_resampled, y_pred, average='weighted'))
print("Recall:", recall_score(y_train_resampled, y_pred, average='weighted'))
print("F1-score:", f1_score(y_train_resampled, y_pred, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_train_resampled, y_pred))
print("\n")

y_test_pred = model2.predict(x_test_scale)

print("TEST SET METRICS")
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision:", precision_score(y_test, y_test_pred, average='weighted'))
print("Recall:", recall_score(y_test, y_test_pred, average='weighted'))
print("F1-score:", f1_score(y_test, y_test_pred, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))
print("\nClassification Report:\n", classification_report(y_test, y_test_pred))


if len(set(y_test)) == 2:
    y_test_prob = model2.predict_proba(x_test_scale)[:, 1]
    auc = roc_auc_score(y_test, y_test_prob)
    print("ROC-AUC:", auc)

Cross-validation Accuracy scores: [0.875      0.86934673 0.89949749 0.80904523 0.83919598]
Mean CV Accuracy: 0.8584170854271356
TRAIN SET METRICS
Accuracy: 0.9036144578313253
Precision: 0.9036404987338097
Recall: 0.9036144578313253
F1-score: 0.9036129032258065
Confusion Matrix:
 [[452  46]
 [ 50 448]]


TEST SET METRICS
Accuracy: 0.907563025210084
Precision: 0.907563025210084
Recall: 0.907563025210084
F1-score: 0.907563025210084
Confusion Matrix:
 [[ 96  11]
 [ 11 120]]

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.90      0.90       107
           1       0.92      0.92      0.92       131

    accuracy                           0.91       238
   macro avg       0.91      0.91      0.91       238
weighted avg       0.91      0.91      0.91       238

ROC-AUC: 0.9464935435542555


In [144]:
liver.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65  Female              0.7               0.1                   187   
1   62    Male             10.9               5.5                   699   
2   62    Male              7.3               4.1                   490   
3   58    Male              1.0               0.4                   182   
4   72    Male              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Dataset        disease  
0      3.3                        0.90        1  Liver Disease  
1      3.2                        0.74        1  Liver Disease  
2      3.3                        0.89        1  Liver Disease  
3      3.4                        1.00        1  Liver Disease  
4      2.4                        0.40        1  Liver Disease

In [145]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [146]:
liver.shape

(583, 12)

In [147]:
liver['disease'].unique()

array(['Liver Disease', 'No Liver Disease'], dtype=object)

In [148]:
liver['disease'].value_counts()

disease
Liver Disease       416
No Liver Disease    167
Name: count, dtype: int64

In [149]:
liver['Gender'].value_counts()

Gender
Male      441
Female    142
Name: count, dtype: int64

In [150]:

db = liver['disease'].astype(str).str.strip().str.lower()
liver['disease_int'] = db.replace({'liver disease':1,'no liver disease':0})
liver.drop(['disease'],axis=1,inplace=True)
liver['disease_int'].value_counts()
db1 = liver['Gender']
liver['Gender_int'] = db1.replace({'Male':1,'Female':0})
liver.drop(['Gender'],axis=1,inplace=True)
liver['Gender_int'].value_counts()
liver['disease_int'].value_counts()

C:\Users\HARISH\AppData\Local\Temp\ipykernel_15532\2602246346.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  liver['disease_int'] = db.replace({'liver disease':1,'no liver disease':0})
C:\Users\HARISH\AppData\Local\Temp\ipykernel_15532\2602246346.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  liver['Gender_int'] = db1.replace({'Male':1,'Female':0})


disease_int
1    416
0    167
Name: count, dtype: int64

In [151]:
liver.fillna(method='bfill',inplace =True)

C:\Users\HARISH\AppData\Local\Temp\ipykernel_15532\2861537541.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  liver.fillna(method='bfill',inplace =True)


In [152]:
liver.head()

Age  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65              0.7               0.1                   187   
1   62             10.9               5.5                   699   
2   62              7.3               4.1                   490   
3   58              1.0               0.4                   182   
4   72              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  disease_int  Gender_int  
0      3.3                        0.90        1            1           0  
1      3.2                        0.74        1            1           1  
2      3.3                        0.89        1            1           1  
3      3.4                        1.00        1            1           1  
4      2.4                        0.40        1            1           1

In [153]:
X = liver.drop(['disease_int','Dataset'],axis=1)
Y = liver['disease_int']

In [154]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,random_state=42,test_size=0.2,stratify=Y)

In [155]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
x_train_resampled, y_train_resampled = smote.fit_resample(x_train, y_train)


In [156]:
liver_scaler = StandardScaler()
x_train_scale = liver_scaler.fit_transform(x_train_resampled)
x_test_scale = liver_scaler.transform(x_test)

In [157]:
from sklearn.linear_model import LogisticRegression

In [158]:
model3 = LogisticRegression()
model3.fit(x_train_scale,y_train_resampled)
y_pred = model3.predict(x_test_scale)

In [159]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.7350427350427351

In [160]:
print(liver['disease_int'].value_counts())

disease_int
1    416
0    167
Name: count, dtype: int64


In [161]:
print(list(X.columns))

['Age', 'Total_Bilirubin', 'Direct_Bilirubin', 'Alkaline_Phosphotase', 'Alamine_Aminotransferase', 'Aspartate_Aminotransferase', 'Total_Protiens', 'Albumin', 'Albumin_and_Globulin_Ratio', 'Gender_int']


In [162]:


sample_input_low = np.array([[28, 0.8, 0.2, 100, 35, 25, 7.5, 4.9, 1.6, 1]])  
sample_input_med = np.array([[45, 2.0, 0.9, 185, 70, 80, 6.5, 3.4, 1.6, 1]])  
sample_input_high = np.array([[62, 9.0, 1.9, 255, 130, 190, 8.9, 4.9, 1.5, 0]]) 

sample = sample_input_high

scaled_sample = liver_scaler.transform(sample)

prediction = model3.predict(scaled_sample)
probability = model3.predict_proba(scaled_sample)[0][1]

print("LIVER MODEL TEST")
print("Scaled Input:", scaled_sample)
print("Predicted Class:", prediction)
print("Probability of disease:", probability)
if probability < 0.4:
    print("Risk Level: LOW")
elif probability < 0.7:
    print("Risk Level: MEDIUM")
else:
    print("Risk Level: HIGH")

LIVER MODEL TEST
Scaled Input: [[ 1.15430369  1.53990459  0.36788762 -0.08034378  0.37624702  0.55675364
   2.32822928  2.21696414  1.74409509 -1.42866927]]
Predicted Class: [1]
Probability of disease: 0.8539584762463752
Risk Level: HIGH


C:\Users\HARISH\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [163]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, roc_auc_score
import numpy as np

cv_scores = cross_val_score(model3, x_train_scale, y_train_resampled, cv=5, scoring='accuracy')
print("Cross-validation Accuracy scores:", cv_scores)
print("Mean CV Accuracy:", np.mean(cv_scores))

y_pred = model3.predict(x_train_scale)

print("TRAIN SET METRICS")
print("Accuracy:", accuracy_score(y_train_resampled, y_pred))
print("Precision:", precision_score(y_train_resampled, y_pred, average='weighted'))
print("Recall:", recall_score(y_train_resampled, y_pred, average='weighted'))
print("F1-score:", f1_score(y_train_resampled, y_pred, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_train_resampled, y_pred))
print("\n")


y_test_pred = model3.predict(x_test_scale)

print("TEST SET METRICS")
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("Precision:", precision_score(y_test, y_test_pred, average='weighted'))
print("Recall:", recall_score(y_test, y_test_pred, average='weighted'))
print("F1-score:", f1_score(y_test, y_test_pred, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))
print("\nClassification Report:\n", classification_report(y_test, y_test_pred))


if len(set(y_test)) == 2:
    y_test_prob = model3.predict_proba(x_test_scale)[:, 1]
    auc = roc_auc_score(y_test, y_test_prob)
    print("ROC-AUC:", auc)

Cross-validation Accuracy scores: [0.69402985 0.63157895 0.73684211 0.72932331 0.66917293]
Mean CV Accuracy: 0.6921894287958704
TRAIN SET METRICS
Accuracy: 0.6936936936936937
Precision: 0.6993308770985495
Recall: 0.6936936936936937
F1-score: 0.6915126470187549
Confusion Matrix:
 [[259  74]
 [130 203]]


TEST SET METRICS
Accuracy: 0.7350427350427351
Precision: 0.7964189243670375
Recall: 0.7350427350427351
F1-score: 0.7468517616300867
Confusion Matrix:
 [[28  6]
 [25 58]]

Classification Report:
               precision    recall  f1-score   support

           0       0.53      0.82      0.64        34
           1       0.91      0.70      0.79        83

    accuracy                           0.74       117
   macro avg       0.72      0.76      0.72       117
weighted avg       0.80      0.74      0.75       117

ROC-AUC: 0.8189227498228205


In [164]:
import joblib
joblib.dump(model, "models/diabetes_model.joblib")
joblib.dump(diabetes_scaler, "models/diabetes_scaler.joblib")
print("Diabetes model & scaler saved successfully")
joblib.dump(model1, "models/kidney_model.joblib")
joblib.dump(kidney_scaler, "models/kidney_scaler.joblib")
print("Kidney model & scaler saved successfully")
joblib.dump(model2, "models/heart_model.joblib")
joblib.dump(heart_scaler, "models/heart_scaler.joblib")
print("Heart model & scaler saved successfully")
joblib.dump(model3, "models/liver_model.joblib")
joblib.dump(liver_scaler, "models/liver_scaler.joblib")
print("Liver model & scaler saved successfully")



Diabetes model & scaler saved successfully
Kidney model & scaler saved successfully
Heart model & scaler saved successfully
Liver model & scaler saved successfully
